// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: badge.proto

package badge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceBadgeAPI_Greet_FullMethodName = "/badge.ServiceBadgeAPI/Greet"
)

// ServiceBadgeAPIClient is the client API for ServiceBadgeAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceBadgeAPIClient interface {
	Greet(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*Hey, error)
}

type serviceBadgeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceBadgeAPIClient(cc grpc.ClientConnInterface) ServiceBadgeAPIClient {
	return &serviceBadgeAPIClient{cc}
}

func (c *serviceBadgeAPIClient) Greet(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*Hey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hey)
	err := c.cc.Invoke(ctx, ServiceBadgeAPI_Greet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceBadgeAPIServer is the server API for ServiceBadgeAPI service.
// All implementations must embed UnimplementedServiceBadgeAPIServer
// for forward compatibility.
type ServiceBadgeAPIServer interface {
	Greet(context.Context, *Hello) (*Hey, error)
	mustEmbedUnimplementedServiceBadgeAPIServer()
}

// UnimplementedServiceBadgeAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceBadgeAPIServer struct{}

func (UnimplementedServiceBadgeAPIServer) Greet(context.Context, *Hello) (*Hey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedServiceBadgeAPIServer) mustEmbedUnimplementedServiceBadgeAPIServer() {}
func (UnimplementedServiceBadgeAPIServer) testEmbeddedByValue()                         {}

// UnsafeServiceBadgeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceBadgeAPIServer will
// result in compilation errors.
type UnsafeServiceBadgeAPIServer interface {
	mustEmbedUnimplementedServiceBadgeAPIServer()
}

func RegisterServiceBadgeAPIServer(s grpc.ServiceRegistrar, srv ServiceBadgeAPIServer) {
	// If the following call pancis, it indicates UnimplementedServiceBadgeAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceBadgeAPI_ServiceDesc, srv)
}

func _ServiceBadgeAPI_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceBadgeAPIServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceBadgeAPI_Greet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceBadgeAPIServer).Greet(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceBadgeAPI_ServiceDesc is the grpc.ServiceDesc for ServiceBadgeAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceBadgeAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "badge.ServiceBadgeAPI",
	HandlerType: (*ServiceBadgeAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _ServiceBadgeAPI_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "badge.proto",
}
