// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: badge.proto

package badge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Greet()
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_badge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{0}
}

type Hey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hey) Reset() {
	*x = Hey{}
	mi := &file_badge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hey) ProtoMessage() {}

func (x *Hey) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hey.ProtoReflect.Descriptor instead.
func (*Hey) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{1}
}

var File_badge_proto protoreflect.FileDescriptor

const file_badge_proto_rawDesc = "" +
	"\n" +
	"\vbadge.proto\x12\x05badge\"\a\n" +
	"\x05Hello\"\x05\n" +
	"\x03Hey24\n" +
	"\x0fServiceBadgeAPI\x12!\n" +
	"\x05Greet\x12\f.badge.Hello\x1a\n" +
	".badge.HeyB(Z&github.com/PxnPub/pxnMetrics/api/badgeb\x06proto3"

var (
	file_badge_proto_rawDescOnce sync.Once
	file_badge_proto_rawDescData []byte
)

func file_badge_proto_rawDescGZIP() []byte {
	file_badge_proto_rawDescOnce.Do(func() {
		file_badge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_badge_proto_rawDesc), len(file_badge_proto_rawDesc)))
	})
	return file_badge_proto_rawDescData
}

var file_badge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_badge_proto_goTypes = []any{
	(*Hello)(nil), // 0: badge.Hello
	(*Hey)(nil),   // 1: badge.Hey
}
var file_badge_proto_depIdxs = []int32{
	0, // 0: badge.ServiceBadgeAPI.Greet:input_type -> badge.Hello
	1, // 1: badge.ServiceBadgeAPI.Greet:output_type -> badge.Hey
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_badge_proto_init() }
func file_badge_proto_init() {
	if File_badge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_badge_proto_rawDesc), len(file_badge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_badge_proto_goTypes,
		DependencyIndexes: file_badge_proto_depIdxs,
		MessageInfos:      file_badge_proto_msgTypes,
	}.Build()
	File_badge_proto = out.File
	file_badge_proto_goTypes = nil
	file_badge_proto_depIdxs = nil
}
